name: Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    env:
      FILE_HEADER: |
        /*
        Theme Name: Hüttenbau Oberi Theme
        Theme URI: https://github.com/Nevah5/huettenbau-oberi-theme
        Author: Noah Geeler
        Author URI: https://noah.geeler.net
        Description: Hüttenbau Oberi Theme
        Version: 1.0.0
        License: GNU General Public License v3
        License URI: <https://www.gnu.org/licenses/gpl-3.0.html>
        Text Domain: huettenbau-oberi-theme
        Tags: huettenbau-oberi
        */
    name: Build Theme
    runs-on:
      labels: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup dependencies
        run: |
          npm install -g sass
      - name: Compile SCSS
        run: |
          sass . --no-source-map
      - name: Add header to style.css
        run: |
          echo '${{ env.FILE_HEADER }}' | cat - style.css > temp && mv temp style.css
      - name: Prepare ZIP
        run: |
          mkdir build
          cp *.css build/
          cp *.php build/
          cp LICENSE build/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huettenbau-oberi-theme
          retention-days: 1
          path: build/*
