name: Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    env:
      FILE_HEADER: |
        /*
        Theme Name: Hüttenbau Oberi Theme
        Theme URI: https://github.com/Nevah5/huettenbau-oberi-theme
        Author: Noah Geeler
        Author URI: https://noah.geeler.net
        Description: Hüttenbau Oberi Theme
        Version: 1.0.0
        License: GNU General Public License v3
        License URI: <https://www.gnu.org/licenses/gpl-3.0.html>
        Text Domain: huettenbau-oberi-theme
        Tags: huettenbau-oberi
        */
    name: Build Theme
    runs-on:
      labels: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup dependencies
        run: |
          npm install -g sass
      - name: Add header to all files
        run: |
          for file in $(find . -type f -regex '.*\.\(scss\|php\)$'); do
            echo '${{ env.FILE_HEADER }}' | cat - $file > temp && mv temp $file
          done
      - name: Compile SCSS
        run: |
          sass . --no-source-map
      - name: Prepare ZIP
        run: |
          mkdir huettenbau-oberi-theme
          mv *.css huettenbau-oberi-theme/
          mv *.php huettenbau-oberi-theme/
          mv LICENSE huettenbau-oberi-theme/
      - name: ZIP theme
        run: |
          zip -r huettenbau-oberi-theme.zip huettenbau-oberi-theme/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huettenbau-oberi-theme
          retention-days: 1
          path: huettenbau-oberi-theme.zip
